server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api
  retryable: true # 开启重试
  routes:
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    search-service:
      path: /search/**
      serviceId: search-service
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false
    auth-service:
      path: /auth/**
      serviceId: auth-service
      strip-prefix: false
  sensitive-headers: #忽略敏感头信息
  add-host-header: true #携带请求本身的host头信息
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: false # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: C:/test/rsa/rsa.pub
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item